/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const apisidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure using autogenerated
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: '.'
    }
  ]
}

module.exports = apisidebars;